const MITIGATION_STRATEGIES = {
    CSRF_SYNC_TOKEN_1: 'CSRF_SYNC_TOKEN_1',
    CSRF_SYNC_TOKEN_2: 'CSRF_SYNC_TOKEN_2',
    DOUBLE_SUBMIT_COOKIE: 'DOUBLE_SUBMIT_COOKIE',
    CUSTOM_HEADER: 'CUSTOM_HEADER'
}

// set this as needed
const MITIGATION_STRATEGY = MITIGATION_STRATEGIES.CUSTOM_HEADER

module.exports = {
    MITIGATION_STRATEGIES,
    MITIGATION_STRATEGY
}