# login
POST http://localhost:3001/login
Content-Type: application/json

{
    "username": "Lenny"
}

###
# access gated resource with access token
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTGVubnkiLCJpYXQiOjE2OTIyNjg5ODQsImV4cCI6MTY5MjI2ODk5OX0.Z5ppi-P4rmvCdNuQk1Sk7BYyNxqMUfXWsxKLVm_otb0
###

# renew access by passing refresh token
POST http://localhost:3001/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTGVubnkiLCJpYXQiOjE2OTIyNjg5NTAsImV4cCI6MTY5MjI3MDc1MH0.89tXhAsYxuqpsbY3L7PsHK_pqF9upH8-GNIUOVsIbEo"
}

###

# logout to delete refresh token
POST http://localhost:3001/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTGVubnkiLCJpYXQiOjE2OTIyNjg5NTAsImV4cCI6MTY5MjI3MDc1MH0.89tXhAsYxuqpsbY3L7PsHK_pqF9upH8-GNIUOVsIbEo"
}